<?php

/**
 * EmailPool
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    orangehrm
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class EmailPool extends PluginEmailPool
{
    const STATUS_PENDING = 'PENDING';
    const STATUS_PROCESSING = "PROCESSING";
    const STATUS_SENT = 'SENT';
    const STATUS_FAILED = 'FAILED';


    const TYPE_MAKE_PAYMENT = 'make_payment';

    const CONTENT_TYPE_HTML = "text/html";
    const CONTENT_TYPE_PLAIN = "text/plain";
}
