<?php

/**
 * PluginEmployeeSalaryRecord
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginEmployeeSalaryRecord extends BaseEmployeeSalaryRecord
{
    protected $salaryComponentService;
    protected $salaryConfigService;

    public function calculateMonthlyBasicTax($salary){

        $taxBracket = $this->getSalaryService()->getMatchingTaxBracket($salary);
        if ($taxBracket instanceof TaxBracket){
                $tax= $salary*$taxBracket->getPercentage()/100;
                return $tax;
            }

        return null;
    }

    public function calculateMonthlyEpfDeduction($salary){
        $epfPercentage = $this->getSalaryConfigService()->getEpfPercentage();
        $tax = $salary*$epfPercentage/100;
        return $tax;
    }

    public function calculateMonthlyEtfDeduction($salary){
        $etfPercentage = $this->getSalaryConfigService()->getEpfPercentage();
        $tax = $salary*$etfPercentage/100;
        return $tax;
    }

    public function getSalaryService() {
        if (!($this->salaryComponentService instanceof DkSalaryService)) {
            $this->salaryComponentService = new DkSalaryService();
        }
        return $this->salaryComponentService;
    }

    public function getSalaryConfigService() {
        if (!($this->salaryConfigService instanceof DkConfigService)) {
            $this->salaryConfigService = new DkConfigService();
        }
        return $this->salaryConfigService;
    }
}