<?php

/**
 * PluginEmployeeSalaryHistory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginEmployeeSalaryHistory extends BaseEmployeeSalaryHistory
{   protected $monthList = array(1=>'January',2=>'February',3=>'March',4=>'April',5=>'May',6=>'June');

    public function calculateTotalDeduction(){
        $deductions =0;
        $deductions = $this->getMonthlyBasicTax()+$this->getMonthlyNopayLeave()+$this->getMonthlyEtfDeduction()+
            $this->getMonthlyEpfDeduction();
        return $deductions;
    }

    public function dispalyTotalDeduction(){
        return number_format($this->calculateTotalDeduction(),2);
    }

    public function calculateTotalEarnings(){
        $earnings = 0;
        $earnings = $this->getMonthlyBasic() + $this->getOtherAllowance();
        return $earnings;
    }

    public function displayTotalEarnings(){
        return number_format($this->calculateTotalEarnings(),2);
    }

    public function calculateTotalNetsalary(){
        $netSalary = 0;
        $netSalary = ($this->getMonthlyBasic() + $this->getOtherAllowance()) -($this->getMonthlyBasicTax()
                +$this->getMonthlyNopayLeave()+$this->getMonthlyEtfDeduction()+$this->getMonthlyEpfDeduction()) ;
        return $netSalary;
    }

    public function dispalyTotalNetsalary(){
        return number_format($this->calculateTotalNetsalary(),2);
    }

    public function getMonthName(){
        return $this->monthList[$this->getMonth()];
    }
}