<?php

/**
 * PluginEmployeeSalaryRecord
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginEmployeeSalaryRecord extends BaseEmployeeSalaryRecord
{
    protected $salaryComponentService;
    protected $salaryConfigService;
    const ADMIN_SCREEN = 'admin';
    const PIM_SALARY_SCREEN = 'pim_salary';
    const MAX_SALARY = 350000;
    const MAX_SALARY_TAX_PERCENTAGE = 24;

    public function calculateMonthlyBasicTax($salary){

        if($salary<=self::MAX_SALARY){
            $taxBracket = $this->getSalaryService()->getMatchingTaxBracket($salary);
            if ($taxBracket instanceof TaxBracket){
                $tax= $taxBracket->getPercentage();
                return $this->valueFormatter($tax);
            }
        }
        else{
            $taxBracket = $this->getSalaryService()->getMatchingTaxBracket(self::MAX_SALARY);
            if ($taxBracket instanceof TaxBracket){
                $tax= $taxBracket->getPercentage()+(($salary-self::MAX_SALARY)*self::MAX_SALARY_TAX_PERCENTAGE/100);
                return $this->valueFormatter($tax);
            }
        }

        return null;
    }

    public function calculateMonthlyEpfDeduction($salary){
        $epfPercentage = $this->getSalaryConfigService()->getEpfPercentage();
        $tax = $salary*$epfPercentage/100;
        return $this->valueFormatter($tax);
    }

    public function calculateCompanyEpfDeduction($salary){
        $epfPercentage = $this->getSalaryConfigService()->getCompanyEpfPercentage();
        $tax = $salary*$epfPercentage/100;
        return $this->valueFormatter($tax);
    }

    public function calculateMonthlyEtfDeduction($salary){
        $etfPercentage = $this->getSalaryConfigService()->getEtfPercentage();
        $tax = $salary*$etfPercentage/100;
        return $this->valueFormatter($tax);
    }

    public function getSalaryService() {
        if (!($this->salaryComponentService instanceof DkSalaryService)) {
            $this->salaryComponentService = new DkSalaryService();
        }
        return $this->salaryComponentService;
    }

    public function getSalaryConfigService() {
        if (!($this->salaryConfigService instanceof DkConfigService)) {
            $this->salaryConfigService = new DkConfigService();
        }
        return $this->salaryConfigService;
    }

    public function valueFormatter($value){
        return number_format($value,2,'.','');
    }

    public function displayValueFormatter($value){
        return number_format($value,2,'.',',');
    }
}