<?php

/**
 * PluginTaxBracketTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTaxBracketTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return PluginTaxBracketTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTaxBracket');
    }
}