<?php

/**
 * PluginEmployeeSalaryHistory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginEmployeeSalaryHistory extends BaseEmployeeSalaryHistory
{   protected $monthList = array(1=>'January',2=>'February',3=>'March',4=>'April',5=>'May',6=>'June',
                                7=>'July',8=>'August', 9=>'September', 10=>'October', 11=>'November',12=>'December');
    protected $employerContribution;

    /**
     * @return mixed
     */
    public function getEmployerContribution()
    {
        return $this->employerContribution;
    }

    /**
     * @param mixed $employerContribution
     */
    public function setEmployerContribution($employerContribution)
    {
        $this->employerContribution = $employerContribution;
    }

    public function calculateTotalDeduction(){
        $deductions =0;
        $deductions = $this->getMonthlyBasicTax()+$this->getMonthlyNopayLeave()+
            $this->getMonthlyEpfDeduction();
        return $this->valueFormatter($deductions);
    }

    public function dispalyTotalDeduction(){
        return number_format($this->calculateTotalDeduction(),2);
    }

    public function calculateTotalEarnings(){
        $earnings = 0;
        $earnings = $this->getMonthlyBasic() + $this->getOtherAllowance();
        return $this->valueFormatter($earnings);
    }

    public function displayTotalEarnings(){
        return number_format($this->calculateTotalEarnings(),2);
    }

    public function calculateTotalNetsalary(){
        $netSalary = 0;
        $netSalary = ($this->getMonthlyBasic() + $this->getOtherAllowance()) -($this->getMonthlyBasicTax()
                +$this->getMonthlyNopayLeave()+$this->getMonthlyEpfDeduction()) ;
        return $this->valueFormatter($netSalary);
    }

    public function dispalyTotalNetsalary(){
        return number_format($this->calculateTotalNetsalary(),2);
    }

    public function getMonthName(){
        return $this->monthList[$this->getMonth()];
    }

    public function displayCompanyEpfDeduction(){
        return number_format($this->getCompanyEpfDeduction(),2);
    }

    public function displayMonthlyEtfDeduction(){
        return number_format($this->getMonthlyEtfDeduction(),2);
    }

    public function displayMonthlyEpfDeduction(){
        return number_format($this->getMonthlyEpfDeduction(),2);
    }

    public function displayEmployerContribution(){
        return number_format($this->getMonthlyEtfDeduction()+$this->getCompanyEpfDeduction(),2);
    }

    public function displayMonthlyNopayLeave(){
        return number_format($this->getMonthlyNopayLeave(),2);
    }

    public function displayMonthlyBasicTax(){
        return number_format($this->getMonthlyBasicTax(),2);
    }

    public function displayTotalNetsalary(){
        return number_format($this->getTotalNetsalary(),2);
    }

    public function valueFormatter($value){
        return number_format($value,2,'.','');
    }

}