<?php

/**
 * PluginSalaryTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSalaryTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return PluginSalaryTypeTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSalaryType');
    }
}