<?php

/**
 * PluginEmployeeSalaryHistoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginEmployeeSalaryHistoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return PluginEmployeeSalaryHistoryTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginEmployeeSalaryHistory');
    }
}